#!/usr/bin/python

import bz2, sys, re
#main_genome = sys.argv[1]
#main_genome = 'E_coli_K12_W3110'
#main_genome = 'Acidobacterium_MP5ACTX9'

genome_file = open('/Vagabundo/lisa/Cellulose/Updated/GSS_Update/non-redundant/CSS_EFG.txt')
genomes = []
for line in genome_file:
    x = line.strip('\n').split('\t')
    if x[0] not in genomes:
        genomes.append(x[0])
##above lines; gets list of genomes from score files (nonredundant) for getting only the same genomes from the full GSS file
#print genomes
'''
genome_file = open('/Vagabundo/lisa/Cellulose/Updated/TABLE_GENE_TAX.xls')
first = genome_file.readline()
genomes = []
for line in genome_file:
        x = line.split('\t')
        genomes.append(x[0])
#print len(genomes)
genome_file.close()
#genomes = ('E_coli_S88','C_difficile_CD196','E_coli_K12_MG1655','E_coli_K12_W3110')
'''
genome_file.close
def name(main_genome):
    '''
    repliconlist = []
    repliconfile = open("/Users/gmh/PerlLib/Org_lists/Genome2Replicon.pm")
